[package]
name = "resume"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/hit-box/hitbox/"
authors = ["Maxim Beslousov"]
keywords = ["test-keyword"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resume-macro = { path = "./resume-macro" }

[features]
team-lead = []
closed = []
