%%{init: {'theme':'dark', 'themeVariables': { 'fontSize':'14px'}}}%%
timeline
    title Career History
    section KayCom
        2008-2010 : PHP/JavaScript Developer
                  : Web Studio Projects
    section AnjLab
        2010-2015 : Python/JavaScript Developer
                  : FlightMonitor, CloudCube
    section Vladimir State University
        2012-2014 : Lecturer
                  : CS & Cryptography
    section Rambler&Co
        2015-2022 : Team Lead & Software Engineer
                  : News, MediaUp, Weather
                  : Rust, Python, Kubernetes
    section Workato
        2022-2023 : Senior Rust Engineer
                  : WorkatoDB, WorkatoFiles
                  : PostgreSQL, Kafka
    section Rask AI
        2023-2024 : Senior Python Engineer
                  : Backend, API
                  : FastAPI, AI/ML
    section Digital Wave Technology
        2024-Present : Core Software Engineer
                     : OLAP, Domain Engine
                     : Rust, GraphQL, DataFusion
